import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ceraCompact = localFont({
  src: [
    {
      path: "./fonts/Cera Compact Pro Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Cera Compact Pro Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Cera Compact Pro Black.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-cera-compact",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className={`${ceraCompact.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
